"""Add address fields, make phone mandatory, and set unique constraint for contact_info

Revision ID: 192f697e3702
Revises: 6a68f77d2077
Create Date: 2025-07-07 22:44:37.582819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192f697e3702'
down_revision: Union[str, Sequence[str], None] = '6a68f77d2077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('address', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('city', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('country', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('zip_code', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=True)
    op.create_foreign_key(None, 'contacts', 'usuarios', ['user_id'], ['id'])
    op.drop_column('contacts', 'message')
    op.drop_column('contacts', 'is_read')
    op.drop_column('contacts', 'name')
    op.drop_column('contacts', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('contacts', 'user_id')
    op.drop_column('contacts', 'zip_code')
    op.drop_column('contacts', 'country')
    op.drop_column('contacts', 'city')
    op.drop_column('contacts', 'address')
    # ### end Alembic commands ###
