"""Agrega campos name email message is_read a ContactoORM

Revision ID: 5e22ad813378
Revises: 192f697e3702
Create Date: 2025-07-11 22:45:07.639571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e22ad813378'
down_revision: Union[str, Sequence[str], None] = '192f697e3702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero añadimos las columnas como nullable=True
    op.add_column('contacts', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('is_read', sa.Boolean(), nullable=True))
    
    # Luego establecemos valores predeterminados para registros existentes
    op.execute("UPDATE contacts SET name = 'Sin nombre' WHERE name IS NULL")
    op.execute("UPDATE contacts SET email = 'no-email@example.com' WHERE email IS NULL")
    op.execute("UPDATE contacts SET is_read = FALSE WHERE is_read IS NULL")
    
    # Finalmente, hacemos que los campos sean NOT NULL excepto message
    op.alter_column('contacts', 'name', nullable=False)
    op.alter_column('contacts', 'email', nullable=False)
    op.alter_column('contacts', 'is_read', nullable=False)
    
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_column('contacts', 'is_read')
    op.drop_column('contacts', 'message')
    op.drop_column('contacts', 'email')
    op.drop_column('contacts', 'name')
    # ### end Alembic commands ###
